#! /bin/bash


_Pbxbot_zip () {
    if [[ $PLUGINS_REPO ]]
    then
        echo "https://github.com/${PLUGINS_REPO}/archive/master.zip"
    else
        echo "https://github.com/Badhacker98/PBX_2.0/archive/master.zip"
    fi
}

_starter () {
    echo "••• Downloading 🕷𝐒𝐩𝐢𝐝𝐞✘𝐛𝐨𝐭🕷 [v3] •••"
    Pbxpath="Plugins.zip"

    wget -q $(_Pbxbot_zip) -O "$Pbxpath"
    PBXPATH=$(zipinfo -1 "$Pbxpath" | grep -v "/.");
    unzip -qq "$Pbxpath"
    rm -rf "$Pbxpath"
    cd $PBXPATH
    python3 ../updater.py ../requirements.txt requirements.txt

    echo "••• Starting 🕷𝐒𝐩𝐢𝐝𝐞✘𝐛𝐨𝐭🕷 •••"
    chmod 777 start.sh
    ./start.sh
}

_starter
